services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./logs:/app/logs
    environment:
      MONGO_HOST: mongodb
      REDIS_HOST: redis
      LOGGING_DIR_PATH: ${MONGO_HOST}
    expose:
      - "${SERVER_INTERNAL_PORT}"
    networks:
      - mongodb-network
      - redis-network
      - web-network
    depends_on:
      mongodb:
        condition: service_healthy
        restart: true
      redis:
        condition: service_healthy
        restart: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/healthcheck/" ]
      interval: 1s
      retries: 5
      start_period: 10s
      timeout: 5s

  haproxy:
    image: haproxy:latest
    container_name: haproxy_lb
    ports:
      - "8000:80"  # проброс порта на хост
    expose:
      - "8404"
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    networks:
      - web-network
    depends_on:
      - web

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
    volumes:
      - ./database/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    healthcheck:
      test: [ "CMD-SHELL", "mongosh", "--eval", "'db.runCommand(\"ping\").ok'", "localhost:27017/test", "--quiet" ]
      interval: 1s
      retries: 5
      start_period: 10s
      timeout: 5s

  mongodb-exporter:
    image: bitnami/mongodb-exporter:latest
    container_name: mongodb-exporter
    restart: unless-stopped
    ports:
      - "9216:9216"
    environment:
      MONGODB_USER: ${MONGO_USERNAME}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
      MONGODB_URI: "mongodb://mongodb:27017"
    command: ['--log.level=debug', '--collect-all', '--discovering-mode', '--compatible-mode']
    networks:
      - mongodb-network
    depends_on:
      - mongodb

  redis:
    image: redis:8.2-alpine
    container_name: pb_redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis_data:/data/redis
    command: [ "redis-server", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      retries: 5
      start_period: 10s
      timeout: 5s

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    depends_on:
      - web
      - haproxy
      - mongodb-exporter
    networks:
      - web-network
      - mongodb-network
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - web-network
    restart: always

volumes:
  mongodb_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  mongodb-network:
    driver: bridge
  redis-network:
    driver: bridge
  web-network:
    driver: bridge