services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
#    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      SERVER_INTERNAL_PORT: ${SERVER_INTERNAL_PORT}
      SERVER_INTERNAL_HOST: ${SERVER_INTERNAL_HOST}
      LOGGING_DIR_PATH: ${MONGO_HOST}
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}"
    networks:
      - mongodb-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  mongodb-network:
    driver: bridge
    name: mongodb-network