services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
#    restart: unless-stopped
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    environment:
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
      MONGO_HOST: mongodb
      SERVER_INTERNAL_PORT: ${SERVER_INTERNAL_PORT}
      SERVER_INTERNAL_HOST: ${SERVER_INTERNAL_HOST}
      LOGGING_DIR_PATH: ${MONGO_HOST}
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_INTERNAL_PORT}"
    networks:
      - mongodb-network
      - redis-network
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    networks:
      - mongodb-network
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:8.2-alpine
    container_name: pb_redis
    ports:
      - "6379:6379"
    networks:
      - redis-network
    volumes:
      - redis_data:/data/redis
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongodb_data:
  redis_data:

networks:
  mongodb-network:
    driver: bridge
  redis-network:
    driver: bridge