# Autogenerated

from typing import TYPE_CHECKING

from beanie import PydanticObjectId

from src.models.promotion import Promotion
from src.utils.models.data_to_objects import CreateSchemaT, UpdateSchemaT
from src.utils.repositories.beanie_auto_crud_repository import BeanieAutoCRUDRepository

__repository = BeanieAutoCRUDRepository(Promotion)

__all__ = [f for f in __repository.export_methods().keys()]

if TYPE_CHECKING:

    async def create(item: CreateSchemaT | Promotion ) -> Promotion: ...
    async def update_or_error(
        _id: PydanticObjectId, item: UpdateSchemaT | Promotion
    ) -> Promotion: ...
    async def update_or_create(
        _id: PydanticObjectId, item: UpdateSchemaT | Promotion
    ) -> Promotion: ...
    async def find_all() -> list[Promotion]: ...
    async def find_by_id(_id: PydanticObjectId) -> Promotion: ...
    async def find_by_id_or_error(_id: PydanticObjectId) -> Promotion: ...
    async def delete(_id: PydanticObjectId) -> Promotion: ...
