from typing import TYPE_CHECKING

from beanie import PydanticObjectId

from src.models.user import User
from src.utils.repositories.beanie_auto_crud_repository import BeanieAutoCRUDRepository

__repository = BeanieAutoCRUDRepository(User)
__functions = __repository.export_methods()

__all__ = [f for f in __functions.keys()]

if TYPE_CHECKING:

    async def create(item: User) -> User: ...
    async def update_or_error(_id: PydanticObjectId, item: User) -> User: ...
    async def update_or_create(_id: PydanticObjectId, item: User) -> User: ...
    async def find_all() -> list[User]: ...
    async def find_by_id(_id: PydanticObjectId) -> User: ...
    async def find_by_id_or_error(_id: PydanticObjectId) -> User: ...
    async def delete(_id: PydanticObjectId) -> User: ...
